version: '3'
services:
  client:
    image: 'rwijupal3058/client'
    mem_limit: 128m
    hostname: client
  server:
    image: "rwijupal3058/server"
    mem_limit: 128m
    hostname: api   
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'rwijupal3058/worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "rwijupal3058/nginx"
    mem_limit: 128m
    hostname: nginx
    ports: 
      - '80:80'
  
  
